serve:
  cookies:
    same_site_mode: Lax
  admin:
    cors:
      debug: true
      enabled: true
      allowed_origins:
        - http://localhost:4200
        - http://localhost:5001
        - http://localhost:5004
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
  public:
    cors:
      debug: true
      enabled: true
      allowed_origins:
        - http://localhost:4200
        - http://localhost:5001
        - http://localhost:5004
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
      exposed_headers:
        - Content-Type
urls:
  self:
    issuer: http://localhost:5004
  consent: http://localhost:4200/api/consent
  login: http://localhost:4200/signin
  logout: http://localhost:4200/signout

secrets:
  system:
    - e5Mcyq@EU@iT=1hH

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: e5Mcyq@EU@iT=1hH
log:
  level: debug
