name: Pull Request Workflow

on:
  push:
    branches:
      - '**'

jobs:
  format-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
          workflow-id: 'pull-request.yml'
      - run: npm ci

      - name: Install docusaurus dependencies specifically
        run: npm install --prefix ./packages/docs.siwt.xyz

      - run: npx nx format:check
      - run: npx nx affected --target=test --parallel=3 --exclude=smart-contracts
