name: SPDX License Check

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: StakeNow/spdx@master
        with:
          licenses: Apache-2.0 MIT MPL-2.0
