name: SPDX License Check

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: StakeNow/spdx@master
        with:
          licenses: MIT
